name: CI/CD
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: auth-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/auth-service:latest
      - name: Build & push todo
        uses: docker/build-push-action@v4
        with:
          context: .
          file: todo-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/todo-service:latest
      - name: Build & push frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/frontend:latest